application: sa-emote
version: 2
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: sa-emote.py
- url: /list
  script: list.py
- url: /assets
  static_dir: assets
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
  

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?README$